### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by cognitom** [cognitom/dominiq#1]
Or, just remiders for me:

- [x] new: handles functions / async functions / async generators as actions
- [x] new: wraps `state` by `proxy` to protect its values
- [x] improvement: removes dependencies
- [x] new: `<input-proxy>` custom tag
- [x] docs: writes document about event delegation
- [x] improvement: starts making tests
- [x] improvement: checkbox and radio button
